[tool.poetry]
name = "relative-utility-value"
version = "0.1.0"
description = "Relative Utility Value reference implementation"
authors = ["Richard Laugesen <ruv@laugesen.com.au>"]
license = "Apache 2"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.4"
scipy = "^1.9.3"
pathos = "^0.3.2"
statsmodels = "^0.14.1"
jupyter = "^1.0.0"
matplotlib = "^3.7.5"
pandas = "^2.0.3"

[tool.poetry.dev-dependencies]
pytest = "^7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"