[tool.poetry]
name = "ruvpy"
version = "0.9.0"
description = "Reference implementation for the Relative Utility Value forecast value method."
authors = ["Richard Laugesen <richard@laugesen.com.au>"]
license = "Apache 2"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9"
numpy = ">=1.24.4"
scipy = ">=1.9.3"
pathos = ">=0.3.0"
statsmodels = ">=0.13.5"
jupyter = ">=1.0.0"
matplotlib = ">=3.7.2"
pandas = ">=2.0.3"

[tool.poetry.dev-dependencies]
pytest = ">=7.4.0"
flake8 = "^6.0.0"
black = "^23.0.0"
mypy = "^1.0.0"
pytest-cov = "^3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
