[tool.poetry]
name = "relative-utility-value"
version = "0.1.0"
description = "Relative Utility Value reference implementation"
authors = ["Richard Laugesen <ruv@laugesen.com.au>"]
license = "Apache 2"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11"
numpy = ">=1.25.0"
scipy = ">=1.10.0"
pathos = ">=0.3.2"
statsmodels = ">=0.14.0"
jupyter = ">=1.0.0"
matplotlib = ">=3.8.0"
pandas = ">=2.1.0"

[tool.poetry.dev-dependencies]
pytest = ">=7.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
